version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DB_HOST=database-2.cfmu8m8maak0.us-east-2.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=Dreamvacay
      - DB_NAME=dreamvacations
      - DB_PORT=3306
      - DATABASE_URL=mysql://admin:Dreamvacay@database-2.cfmu8m8maak0.us-east-2.rds.amazonaws.com:3306/dreamvacations
    networks:
      - app-network
    restart: unless-stopped 
    dns:
      - 169.254.169.253
      - 8.8.8.8 # Auto-recover if MySQL isn't ready


networks:
  app-network:
    driver: bridge
